name: Deploy API
on: [push]
jobs:

  build:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Prepare APIC Toolkit
      run: |
        
        # Set the source and target paths
        SOURCE_PATH=.github/workflows/apic_toolkit/toolkit-linux.tgz
        TARGET_PATH=$HOME/toolkit-linux.tgz 
        
        # Copy the .tgz file to the runner's home directory
        cp "$SOURCE_PATH" "$TARGET_PATH" 

        # Extract the toolkit
        tar -xzf "$TARGET_PATH"


        # Make the 'apic-slim' file executable
        chmod +x apic-slim

        # Display the extracted files for verification.
        ls -l

    - name: Get IAM token
      env:
        API_KEY: ${{ secrets.api_key }}
        API_HOST: api.${{ secrets.host_suffix}}
      run: |
        mkdir ~/.apiconnect/
        touch ~/.apiconnect/token
        ACCESS_TOKEN=$(curl -s "https://iam.cloud.ibm.com/identity/token" -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json' --data "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=$API_KEY" | jq .access_token -r)
        echo "${API_HOST}/api: |
                refresh_token: \"\"
                access_token: ${ACCESS_TOKEN}" > ~/.apiconnect/token 

    - name: List orgs with apic CLI
      env:
        API_HOST: api.${{ secrets.host_suffix}}
      run: |
        ./apic-slim orgs --accept-license --live-help --my --server ${API_HOST}
